In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
from sklearn import preprocessing

In [2]:
(xtrain,ytrain),(xtest,ytest) = boston_housing.load_data()

57026/57026 [==============================] - 0s 1us/step


In [3]:
print("train shape :",xtrain.shape)
print("Test shape :",xtest.shape)
print("Actual Train Output",ytrain.shape)
print("Actual Test Output",ytest.shape)


train shape : (404, 13)
Test shape : (102, 13)
Actual Train Output (404,)
Actual Test Output (102,)


In [4]:
xtrain

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [5]:
xtrain[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
xtest[0]

array([ 18.0846,   0.    ,  18.1   ,   0.    ,   0.679 ,   6.434 ,
       100.    ,   1.8347,  24.    , 666.    ,  20.2   ,  27.25  ,
        29.05  ])

In [7]:
ytrain[0]

15.2

In [8]:
train_x=preprocessing.normalize(xtrain)
test_x=preprocessing.normalize(xtest)

In [9]:
xtrain[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [10]:
ytrain[0]

15.2

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *

model = Sequential()

model.add(Dense(128,activation='relu',input_shape=(train_x[0].shape)))
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(1))

model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])



In [12]:
import numpy as np
k=4
num_val_samples= len(train_x)
num_epochs = 100
all_scores = []

In [14]:

history=model.fit(x=xtrain,y=ytrain,epochs= num_epochs,batch_size=1,verbose=1,validation_data=(xtest,ytest))

Epoch 1/100
404/404 [==============================] - 2s 3ms/step - loss: 120.4945 - mae: 8.0097 - val_loss: 73.5054 - val_mae: 6.0550
Epoch 2/100
404/404 [==============================] - 1s 3ms/step - loss: 75.5584 - mae: 6.2146 - val_loss: 75.7541 - val_mae: 7.0054
Epoch 3/100
404/404 [==============================] - 1s 3ms/step - loss: 66.3447 - mae: 5.8298 - val_loss: 57.0554 - val_mae: 5.7737
Epoch 4/100
404/404 [==============================] - 1s 2ms/step - loss: 58.7898 - mae: 5.3148 - val_loss: 77.0208 - val_mae: 6.2206
Epoch 5/100
404/404 [==============================] - 1s 2ms/step - loss: 57.2946 - mae: 5.3584 - val_loss: 49.0255 - val_mae: 5.0748
Epoch 6/100
404/404 [==============================] - 1s 2ms/step - loss: 53.6996 - mae: 5.1105 - val_loss: 50.2401 - val_mae: 5.1434
Epoch 7/100
404/404 [==============================] - 1s 2ms/step - loss: 51.0719 - mae: 4.8556 - val_loss: 51.5291 - val_mae: 5.2674
Epoch 8/100
404/404 [==============================] -

In [15]:
## We will need to convert train and test data using pandas

In [17]:
test = [[0.02675675, 0.        , 0.02677953, 0.        , 0.0010046 ,
        0.00951931, 0.14795322, 0.0027145 , 0.03550877, 0.98536841,
        0.02988655, 0.04031725, 0.04298041]]
print("Actual Output: ", ytrain[0])
print("Predicted Output: ", model.predict(test))

Actual Output:  15.2
1/1 [==============================] - 0s 113ms/step
Predicted Output:  [[1.7357788]]
